---
title: "Marlins-Questionnaire"
author: "Ernesto Herrero"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(tidyverse)
library(dplyr)
library(tidyr)

```

```{r needed_stats}

Single_Prob <-  ( 42039	 - (6776+785+8531))/186517
Double_Prob <-  8531/186517
Triple_Prob <-  785/186517
HR_Prob <-  6776/186517
BB_Prob <- 15895/186517
K_Prob <- 42823/186517

##Asuume % of all

GB_Prob <- .68*.37
FB_Prob <- .68*.34

check <- Single_Prob + Double_Prob + Triple_Prob + HR_Prob + BB_Prob + K_Prob + FB_Prob + GB_Prob
```


```{r function}




at_bat <- function(prob)
{
  prob <- round(prob, 4)
  if(between(prob, 0, .0042))# #triple
  {
    return(3)
  }else if(between(prob, .0042, .2337)) ##K
  {
   return(-1) 
  }else if(between(prob, .2338, .3190))#BB
  {
    return(5)
  }else if(between(prob, .3191, .3647)) #ouble
  {
    return(2)
  }else if(between(prob, .3648, .5038)) ##Single
  {
    return(1)
  }else if(between(prob, .5039, .7150)) ##Flyball
  {
    return(-2)
  }else if(between(prob, .7151, .9660)) ##GB
  {
    return(-3)
  }else if(between(prob, .9661, 1))# #HR
  {
    return(4)
  }else
  {
    cat("DID NOT WORK", prob)
  }
}
```

```{r bases}
# bases_sit_color <- function(bases_sit)
# {
#   if(bases_sit[1] & bases_sit[2] & bases_sit[3])
#   {
#      ggplot() + geom_polygon(aes(c(0,.5,0,-.5), c(1,2,3,2)),color = "yellow", alpha=0.5) +xlim(c(-5,5)) + ylim(c(0,10))  + geom_polygon(aes(x= c(0, .5, 0, -.5), y = c(7,8,9,8)), fill = "yellow") + geom_polygon(aes(x= c(2, 2.5, 2, 1.5), y = c(4,5,6,5)), fill = "yellow") + geom_polygon(aes(x= c(-2, -1.5, -2, -2.5), y = c(4,5,6,5)), fill = "yellow")+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), axis.text=element_blank(), axis.title = element_blank())
#   }else if(bases_sit[1] & !bases_sit[2] & !bases_sit[3])
#   {
#     ggplot() + geom_polygon(aes(c(0,.5,0,-.5), c(1,2,3,2)),color = "yellow", alpha=0.5) +xlim(c(-5,5)) + ylim(c(0,10)) + 
#       geom_polygon(aes(x= c(2, 2.5, 2, 1.5), y = c(4,5,6,5)), fill = "yellow") +
#       geom_polygon(aes(x= c(0, .5, 0, -.5), y = c(7,8,9,8)),color = "yellow", alpha=0.5) + 
#       geom_polygon(aes(x= c(-2, -1.5, -2, -2.5), y = c(4,5,6,5)),color = "yellow", alpha=0.5)+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), axis.text=element_blank(), axis.title = element_blank())
#   }else if(!bases_sit[1] & bases_sit[2] + !bases_sit[3])
#   {
#       ggplot() + geom_polygon(aes(c(0,.5,0,-.5), c(1,2,3,2)),color = "yellow", alpha=0.5) +xlim(c(-5,5)) + ylim(c(0,10)) + 
#       geom_polygon(aes(x= c(2, 2.5, 2, 1.5), y = c(4,5,6,5)),color = "yellow", alpha=0.5) +
#       geom_polygon(aes(x= c(0, .5, 0, -.5), y = c(7,8,9,8)), fill = "yellow") + 
#       geom_polygon(aes(x= c(-2, -1.5, -2, -2.5), y = c(4,5,6,5)),color = "yellow", alpha=0.5)+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), axis.text=element_blank(), axis.title = element_blank())
#   }else if(!bases_sit[1] & !bases_sit[2] + bases_sit[3])
#   {
#     ggplot() + geom_polygon(aes(c(0,.5,0,-.5), c(1,2,3,2)),color = "yellow", alpha=0.5) +xlim(c(-5,5)) + ylim(c(0,10)) + 
#       geom_polygon(aes(x= c(2, 2.5, 2, 1.5), y = c(4,5,6,5)),color = "yellow", alpha=0.5) +
#       geom_polygon(aes(x= c(0, .5, 0, -.5), y = c(7,8,9,8)),color = "yellow", alpha=0.5) + 
#       geom_polygon(aes(x= c(-2, -1.5, -2, -2.5), y = c(4,5,6,5)), fill = "yellow")+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), axis.text=element_blank(), axis.title = element_blank())
#   }else if(bases_sit[1] & bases_sit[2] + !bases_sit[3])
#   {
#     ggplot() + geom_polygon(aes(c(0,.5,0,-.5), c(1,2,3,2)),color = "yellow", alpha=0.5) +xlim(c(-5,5)) + ylim(c(0,10)) + 
#       geom_polygon(aes(x= c(2, 2.5, 2, 1.5), y = c(4,5,6,5)), fill = "yellow") +
#       geom_polygon(aes(x= c(0, .5, 0, -.5), y = c(7,8,9,8)), fill = "yellow") + 
#       geom_polygon(aes(x= c(-2, -1.5, -2, -2.5), y = c(4,5,6,5)),color = "yellow", alpha=0.5)+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), axis.text=element_blank(), axis.title = element_blank())
#   }else if(!bases_sit[1] & bases_sit[2] + bases_sit[3])
#   {
#     ggplot() + geom_polygon(aes(c(0,.5,0,-.5), c(1,2,3,2)),color = "yellow", alpha=0.5) +xlim(c(-5,5)) + ylim(c(0,10)) + 
#       geom_polygon(aes(x= c(2, 2.5, 2, 1.5), y = c(4,5,6,5)),color = "yellow", alpha=0.5) +
#       geom_polygon(aes(x= c(0, .5, 0, -.5), y = c(7,8,9,8)), fill = "yellow") + 
#       geom_polygon(aes(x= c(-2, -1.5, -2, -2.5), y = c(4,5,6,5)), fill = "yellow")+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), axis.text=element_blank(), axis.title = element_blank())
#   }else if(bases_sit[1] & !bases_sit[2] + bases_sit[3])
#   {
#     ggplot() + geom_polygon(aes(c(0,.5,0,-.5), c(1,2,3,2)),color = "yellow", alpha=0.5) +xlim(c(-5,5)) + ylim(c(0,10)) + 
#       geom_polygon(aes(x= c(2, 2.5, 2, 1.5), y = c(4,5,6,5)), fill = "yellow") +
#       geom_polygon(aes(x= c(0, .5, 0, -.5), y = c(7,8,9,8)),color = "yellow", alpha=0.5) + 
#       geom_polygon(aes(x= c(-2, -1.5, -2, -2.5), y = c(4,5,6,5)), fill = "yellow")+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), axis.text=element_blank(), axis.title = element_blank())
#   }else if(!bases_sit[1] & !bases_sit[2] + !bases_sit[3])
#   {
# #     ggplot() + geom_polygon(aes(c(0,.5,0,-.5), c(1,2,3,2)),color = "yellow", alpha=0.5) +xlim(c(-5,5)) + ylim(c(0,10)) + 
# #       geom_polygon(aes(x= c(2, 2.5, 2, 1.5), y = c(4,5,6,5)),color = "yellow", alpha=0.5) +
# #       geom_polygon(aes(x= c(0, .5, 0, -.5), y = c(7,8,9,8)),color = "yellow", alpha=0.5) + 
# #       geom_polygon(aes(x= c(-2, -1.5, -2, -2.5), y = c(4,5,6,5)),color = "yellow", alpha=0.5)+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_blank(), axis.ticks = element_blank(), axis.text=element_blank(), axis.title = element_blank())
# #   }
# # }
# #     


```


```{r}
 
prediction <- function(inning)
{
  home_score = 0
  away_score = 0
  next_inning = 10
  current_inning = 10


  ls <- c(home_score, away_score, current_inning)

  while(ls[1] == ls[2])
  {
    current_inning = next_inning
    if(current_inning >= inning)
    {
       bases_sit <- c(FALSE, TRUE, FALSE)
    }else
    {
      bases_sit <- c(FALSE, FALSE, FALSE)
    }
    
    numOuts = 0 
    home_batting = FALSE
    
    cat("\nAway Team Batting:")
    cat("\nscore:", ls[2],"-", ls[1])
    while(numOuts < 3 & !home_batting)
    {
      outcome <- at_bat(runif(1,min=0,max=1))
      
      
      # cat("\nMan on first:", bases_sit[1],
      #  "\nMan on Second:", bases_sit[2],
      #     "\nMan on third:", bases_sit[3])
       cat("\nOuts:", numOuts)
      cat("\nAB Result:", outcome)
     
      
      if(outcome < 0)
      {
        numOuts = numOuts + 1
      }
      
      if(!bases_sit[1] & !bases_sit[2] & !bases_sit[3])
      {
        #catbases empty
        if(outcome == 5 | outcome == 1)
        {
          bases_sit[1] <- TRUE
        }else if(outcome == 4)
        {
          ls[2] =ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[3] <- TRUE 
        }else if(outcome == 2)
        {
          bases_sit[2] <- TRUE
        }
        
      }else if(bases_sit[1] & !bases_sit[2] & !bases_sit[3])
      {
        # on first
        if(outcome == 5 | outcome == 1)
        {
          bases_sit[1] <- TRUE
          bases_sit[2] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[1] <- FALSE
          ls[2] = ls[2] +  2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[1] <- FALSE
          bases_sit[3] <- TRUE
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[1] <- FALSE
          bases_sit[2] <- TRUE
          bases_sit[3] <- TRUE
        }else if(outcome == -3)
        {
          if(runif(1,0,1) < .5 & numOuts < 2) #ouble play
          {
            numOuts = numOuts + 1
            bases_sit[1] <- FALSE
          }
        }
        
      }else if(!bases_sit[1] & bases_sit[2] & !bases_sit[3])
      {
        # on second
        if(outcome == 5)
        {
          bases_sit[1] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[2] <- FALSE
          ls[2] = ls[2] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[2] <- FALSE
          bases_sit[3] <- TRUE
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          if(runif(1,0,1) < .5)
          {
            bases_sit[1] <- TRUE
            bases_sit[2] <- FALSE
            ls[2] = ls[2] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else
          {
            bases_sit[1] <- TRUE
            bases_sit[3] <- TRUE
            bases_sit[2] <- FALSE
          }
        }
        
      }else if(!bases_sit[1] & !bases_sit[2] & bases_sit[3])
      {
        # on third
        if(outcome == 5)
        {
          bases_sit[1] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[3] <- FALSE
          ls[2] = ls[2] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          ls[2] = ls[2] +  1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[3] <- FALSE
          bases_sit[2] <- TRUE
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          bases_sit[1] <- TRUE
          bases_sit[3] <- FALSE
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == -2)
        {
          if(runif(1,0,1) < .81 & numOuts < 2)
          {
            bases_sit[3] <- FALSE
            ls[2] = ls[2] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else if(runif(1,0,1) < .81 & numOuts < 2)
          {
             bases_sit[3] <- FALSE
             numOuts = numOuts +1
          }
        }
        
      }else if(bases_sit[1] & bases_sit[2] & !bases_sit[3])
      {
        # first and second
        if(outcome == 5)
        {
          bases_sit[3] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[1] <- FALSE
          bases_sit[2] <- FALSE
          ls[2] = ls[2] + 3
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[1] <- FALSE
          bases_sit[2] <- FALSE
          bases_sit[3] <- TRUE
          ls[2] = ls[2] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[3] <- TRUE
          bases_sit[1] <- FALSE
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          if(runif(1,0,1) < .5)
          {
            ls[2] = ls[2] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else
          {
            bases_sit[3] <- TRUE
          }
        }else if(outcome == -3)
        {
          if(runif(1,0,1) < .50 & numOuts < 2)
          {
            numOuts = numOuts +1
            bases_sit[3] <- TRUE
            bases_sit[1] <- FALSE
            bases_sit[2] <- FALSE
          }
        }
        
      }else if(bases_sit[1] & !bases_sit[2] & bases_sit[3])
      {
        # on first and third
        if(outcome == 5)
        {
          bases_sit[2] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[1] <- FALSE
          bases_sit[3] <- FALSE
          ls[2] = ls[2] + 3
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[1] <- FALSE
          ls[2] = ls[2] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[2] <- TRUE
          bases_sit[1]<- FALSE
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          bases_sit[2] <- TRUE
          bases_sit[3] <- FALSE
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == -2)
        {
          chance <- runif(1,0,1)
          if(chance < .81 & numOuts < 2)
          {
            bases_sit[3] <- FALSE
            ls[2] = ls[2] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else if(chance > .81 & numOuts < 2)
          {
             bases_sit[3] <- FALSE
             numOuts = numOuts +1
          }
        }else if(outcome == -3)
        {
          chance <- runif(1,0,1)
          if(chance < .5 & numOuts < 2)
          {
            bases_sit[1] < FALSE
            bases_sit[2] <-  FALSE
            bases_sit[3]<- FALSE
            numOuts = numOuts +1
            ls[2] = ls[2] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else if(chance > .5 & numOuts < 2)
          {
            bases_sit[3] <- FALSE
            bases_sit[2] <- TRUE
          }
        }
        
        
      }else if(!bases_sit[1] & bases_sit[2] & bases_sit[3])
      {
        # on second and third
        if(outcome == 5)
        {
          bases_sit[1] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[2] <- FALSE
          bases_sit[3]<- FALSE
          ls[2] = ls[2] + 3
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[2] <- FALSE
          ls[2] = ls[2] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[3] <- FALSE
          ls[2] = ls[2] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
          bases_sit[1] <- TRUE
          if(runif(1,0,1) < .5)
          {
            bases_sit[2] <- FALSE
            bases_sit[3] <- FALSE
            ls[2] = ls[2] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else
          {
            bases_sit[2] <- FALSE
          }
        }else if(outcome == -2)
        {
          chance <- runif(1,0,1)
          if(chance < .81 & numOuts < 2)
          {
            bases_sit[3] <- FALSE
            ls[2] = ls[2] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else if(chance > .81 & numOuts < 2)
          {
             bases_sit[3] <- FALSE
             numOuts = numOuts +1
             
          }
        }
        
      }else if(bases_sit[1] & bases_sit[2] & bases_sit[3])
      {
        if(outcome == 5)
        {
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 4)
        {
          bases_sit[1] <- FALSE
          bases_sit[2] <- FALSE
          bases_sit[3] <- FALSE
          ls[2] = ls[2] + 4
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[1] <- FALSE
          bases_sit[2] <- FALSE
          ls[2] = ls[2] + 3
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[1] <- FALSE
          ls[2] = ls[2] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          ls[2] = ls[2] + 1
          cat("\nscore:", ls[2],"-", ls[1])
          chance <- runif(1,0,1)
          if(chance < .5)
          {
            bases_sit[3] <- FALSE
            ls[2] = ls[2] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }
        }else if(outcome == -2)
        {
          chance <- runif(1,0,1)
          if(chance < .81 & numOuts < 2)
          {
            bases_sit[3] <- FALSE
            ls[2] = ls[2] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else if(chance > .81)
          {
            bases_sit[3] <- FALSE
            numOuts = numOuts +1
          }
        }else if(outcome == -3)
        {
          if(runif(1,0,1) < .5 & numOuts < 2)
          {
            bases_sit[1] < FALSE
            bases_sit[2] <-  FALSE
            numOuts = numOuts +1
            ls[2] = ls[2] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }
        }
        }
      }
      
    home_batting <- TRUE
    numOuts = 0
    if(current_inning >= inning)
    {
       bases_sit <- c(FALSE, TRUE, FALSE)
    }else
    {
      bases_sit <- c(FALSE, FALSE, FALSE)
    }
    cat("\nHome Team Batting")  
    cat("\nscore:", ls[2],"-", ls[1])
    
    while(numOuts < 3 & home_batting & ls[1] <= ls[2])
    {
      
      outcome <- at_bat(runif(1,min=0,max=1))
      
      # cat("\nMan on first:", bases_sit[1],
      #     "\nMan on Second:", bases_sit[2],
      #     "\nMan on third:", bases_sit[3])
      cat("\nOuts:", numOuts)
      cat("\nAB Result:", outcome)
     
      
      if(outcome < 0)
      {
        numOuts = numOuts +1
      }

      if(!bases_sit[1] & !bases_sit[2] & !bases_sit[3])
      {
        ##bases empty
        if(outcome == 5 | outcome == 1)
        {
          bases_sit[1] <- TRUE
        }else if(outcome == 4)
        {
          ls[1] = ls[1] +  1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[3] <- TRUE
        }else if(outcome == 2)
        {
          bases_sit[2] <- TRUE
        }

      }else if(bases_sit[1] & !bases_sit[2] & !bases_sit[3])
      {
        # on first
        if(outcome == 5 | outcome == 1)
        {
          bases_sit[1] <- TRUE
          bases_sit[2] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[1] <- FALSE
          ls[1] = ls[1] +  2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[1] <- FALSE
          bases_sit[3] <- TRUE
          ls[1] = ls[1] +  1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[1] <- FALSE
          bases_sit[2] <- TRUE
          bases_sit[3] <- TRUE
        }else if(outcome == -3)
        {
          if(runif(1,0,1) < .5 & numOuts < 2) #ouble play
          {
            numOuts = numOuts +1
            bases_sit[1] <- FALSE
          }
        }

      }else if(!bases_sit[1] & bases_sit[2] & !bases_sit[3])
      {
        # on second
        if(outcome == 5)
        {
          bases_sit[1] <- TRUE
        }else if(outcome == 4)
        {
          ls[1] = ls[1] + 2
          
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[2] <- FALSE
          bases_sit[3] <- TRUE
          ls[1] = ls[1] +  1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          ls[1] = ls[1] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          if(runif(1,0,1) < .5)
          {
            bases_sit[1] <- TRUE
            bases_sit[2] <- FALSE
            ls[1] = ls[1] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else
          {
            bases_sit[1] <- TRUE
            bases_sit[3] <- TRUE
            bases_sit[2] <- FALSE
          }
        }

      }else if(!bases_sit[1] & !bases_sit[2] & bases_sit[3])
      {
        # on third
        if(outcome == 5)
        {
          bases_sit[1] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[3] <- FALSE
          ls[1] = ls[1] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          ls[1] = ls[1] +  1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[3] <- FALSE
          bases_sit[2] <- TRUE
          ls[1] = ls[1] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          bases_sit[1] <- TRUE
          bases_sit[3] <- FALSE
          ls[1] = ls[1] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == -2)
        {
          if(runif(1,0,1) < .81 & numOuts < 2)
          {
            bases_sit[3] <- FALSE
            ls[1] = ls[1] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else if(runif(1,0,1) < .81 & numOuts < 2)
          {
             bases_sit[3] <- FALSE
             numOuts = numOuts +1
          }
        }

      }else if(bases_sit[1] & bases_sit[2] & !bases_sit[3])
      {
        # first and second
        if(outcome == 5)
        {
          bases_sit[3] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[1] <- FALSE
          bases_sit[2] <- FALSE
          ls[1] = ls[1] + 3
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[1] <- FALSE
          bases_sit[2] <- FALSE
          bases_sit[3] <- TRUE
          ls[1] = ls[1] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[3] <- TRUE
          bases_sit[1] <- FALSE
          ls[1] = ls[1] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          if(runif(1,0,1) < .5)
          {
            ls[1] = ls[1] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else
          {
            bases_sit[3] <- TRUE
          }
        }else if(outcome == -3)
        {
          if(runif(1,0,1) < .50 & numOuts < 2)
          {
            numOuts = numOuts +1
            bases_sit[3] <- TRUE
            bases_sit[1] <- FALSE
            bases_sit[2] <- FALSE
          }
        }

      }else if(bases_sit[1] & !bases_sit[2] & bases_sit[3])
      {
        # on first and third
        if(outcome == 5)
        {
          bases_sit[2] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[1] <- FALSE
          bases_sit[3] <- FALSE
          ls[1] = ls[1] + 3
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[1] <- FALSE
          ls[1] = ls[1] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[2] <- TRUE
          bases_sit[1]<- FALSE
          ls[1] = ls[1] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          bases_sit[2] <- TRUE
          bases_sit[3] <- FALSE
          ls[1] = ls[1] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == -2)
        {
          chance <- runif(1,0,1)
          if(chance < .81 & numOuts < 2)
          {
            bases_sit[3] <- FALSE
            ls[1] = ls[1] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else if(chance > .81 & numOuts < 2)
          {
             bases_sit[3] <- FALSE
             numOuts = numOuts +1
          }
        }else if(outcome == -3)
        {
          chance <- runif(1,0,1)
          if(chance < .5 & numOuts < 2)
          {
            bases_sit[1] < FALSE
            bases_sit[2] <-  FALSE
            bases_sit[3]<- FALSE
            numOuts = numOuts +1
            ls[1] = ls[1] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else if(chance > .5 & numOuts < 2)
          {
            bases_sit[3] <- FALSE
            bases_sit[2] <- TRUE
          }
        }


      }else if(!bases_sit[1] & bases_sit[2] & bases_sit[3])
      {
        # on second and third
        if(outcome == 5)
        {
          bases_sit[1] <- TRUE
        }else if(outcome == 4)
        {
          bases_sit[2] <- FALSE
          bases_sit[3]<- FALSE
          ls[1] = ls[1] + 3
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[2] <- FALSE
          ls[1] = ls[1] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[3] <- FALSE
          ls[1] = ls[1] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          ls[1] = ls[1] + 1
          cat("\nscore:", ls[2],"-", ls[1])
          bases_sit[1] <- TRUE
          if(runif(1,0,1) < .5)
          {
            bases_sit[2] <- FALSE
            bases_sit[3] <- FALSE
            ls[1] = ls[1] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else
          {
            bases_sit[2] <- FALSE
          }
        }else if(outcome == -2)
        {
          chance <- runif(1,0,1)
          if(chance < .81 & numOuts < 2)
          {
            bases_sit[3] <- FALSE
            ls[1] = ls[1] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else if(chance > .81 & numOuts < 2)
          {
             bases_sit[3] <- FALSE
             numOuts = numOuts +1
          }
        }

      }else if(bases_sit[1] & bases_sit[2] & bases_sit[3])
      {
        if(outcome == 5)
        {
          ls[1] = ls[1] + 1
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 4)
        {
          bases_sit[1] <- FALSE
          bases_sit[2] <- FALSE
          bases_sit[3] <- FALSE
          ls[1] = ls[1] + 4
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 3)
        {
          bases_sit[1] <- FALSE
          bases_sit[2] <- FALSE
          ls[1] = ls[1] + 3
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 2)
        {
          bases_sit[1] <- FALSE
          ls[1] = ls[1] + 2
          cat("\nscore:", ls[2],"-", ls[1])
        }else if(outcome == 1)
        {
          ls[1] = ls[1] + 1
          cat("\nscore:", ls[2],"-", ls[1])
          chance <- runif(1,0,1)
          if(chance < .5)
          {
            bases_sit[3] <- FALSE
            ls[1] = ls[1] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }
        }else if(outcome == -2)
        {
          chance <- runif(1,0,1)
          if(chance < .81 & numOuts < 2)
          {
            bases_sit[3] <- FALSE
            ls[1] = ls[1] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }else if(chance > .81)
          {
            bases_sit[3] <- FALSE
            numOuts = numOuts +1
          }
        }else if(outcome == -3)
        {
          if(runif(1,0,1) < .5 & numOuts < 2)
          {
            bases_sit[1] < FALSE
            bases_sit[2] <-  FALSE
            numOuts = numOuts +1
            ls[1] = ls[1] + 1
            cat("\nscore:", ls[2],"-", ls[1])
          }
        }
        }
      }
      next_inning = current_inning + 1
      if(ls[1] > ls[2])
      {
        cat("\nWalkoff! Home team Wins!")
      }
   }
    ls[3] <- current_inning
    if(ls[2] > ls[1])
    {
      cat("\nFinal!")
    }
    return(cat("\nAway Team:",ls[2], "\nHome Team:", ls[1], "\nInnings Played:", ls[3]))
   }
   
```

```{r call_func}
x <- c()
for(i in 1:10000) #Starting the Runner on second in the 10th inning
{
  x[i] <- prediction(10)[3]
}
Perc_games_below13_when_10 <- length(x[x >= 13])/length(x)
x <- c()
for(i in 1:10000) #Starting the Runner on second in the 11th inning
{
  x[i] <- prediction(11)[3]
}
Perc_games_below13_when_11 <- length(x[x >= 13])/length(x)
x <- c()
for(i in 1:10000) #Starting the Runner on second in the 11th inning
{
  x[i] <- prediction(12)[3]
}
Perc_games_below13_when_12 <- length(x[x >= 13])/length(x)
```

```{r}

x = 5*rchisq(8,3)
y = 6*rchisq(5,2)
U = sum(x)/sum(y)


```



